spring:
  cloud:
    gateway:
      routes:
        - id: Route_Nicaragua
          uri: http://httpbin.org:80
          predicates:
            - Path=/html/**
            - Header=X-Subscription-Id, NI10100010001FA25684685245836

        - id: Route_Panama
          uri: http://httpbin.org:80
          predicates:
            - Path=/html/**
            - Header=X-Subscription-Id, PA10100010001FA25684685245836

        - id: Route_Ecuador
          uri: http://httpbin.org:80
          predicates:
            - Path=/html/**
            - Header=X-Subscription-Id, EC10100010001FA25684685245836

management:
  endpoints:
    web:
      exposure:
        include: "*"
